### ISSUE TITLE
In memory backend.

### ISSUE THREAD

**Issue by CrowdHailer** [toniqsystems/raft#16]
Not even sure if this question makes sense. However.

Is it possible to have a raft cluster where messages are committed to a log that exists in memory only?
Assuming enough of the cluster stays alive to accept new writes then enough of the custer should be alive to guarantee that the log is not lost?

Is that true? if so such a backend would be useful

**Comment by keathley** [comment]
I've thought about doing this for testing purposes. If you do this in production you'll have issues because if a node crashes it'll (obviously) loose all of its state. When it comes back up its effectively a new node again and needs to be caught back up. Which means it'll need the entirety of the log messages replicated to it. Ideally we could also send snapshots but I haven't had a chance to build the snapshot rpcs yet.

**Comment by CrowdHailer** [comment]
I'm not sure why loosing all it's state would be a problem. Are the following two cases not handled equivalently by the protocol

1. Node dies and is replaced by a new node
2. Node is disconnected for a prolonged period before being reconnected and needing to catch up old messages

**Comment by NeilMenne** [comment]
I think an in-memory log would be irresponsible to use for Raft outside of simple test cases because you could very easily violate:

> Raft guarantees that committed entries are durable
and will eventually be executed by all of the available
state machines

1. This is considered a configuration change.
2. This is not.

Raft assumes that cluster configuration is done infrequently. It's a separate process that has its own rules. One of which assumes that a majority exists across both configurations for the transitional period.

An obvious pathological case would be to have a three node cluster, partition one follower from the other two nodes and then have the leader+follower side die due to a bug in the state machine. With the in-memory backend, you've just lost data (not necessarily just the command that triggered the bug).

**Comment by keathley** [comment]
@CrowdHailer Adding and removing nodes is done through its own set of RPCs and has its own rules. During that time new nodes have logs replicated to them but have no suffrage; they can't vote in new leader elections, etc. Cluster configuration changes have to be intentional in contrast with standard cluster membership semantics seen in the rest of the elixir ecosystem. When a node is added its added to a durable list through a series of rpcs and steps to ensure consistency (as @NeilMenne discussed above). If a node crashes there's no way for the rest of the nodes to know that its now lost all of its data and the other nodes will assume that it has all of its data still. The node that suffered a crash will eventually have all of the logs replicated to it again but during this phase it *should not* be allowed to vote. Consensus is safeguarded by ensuring that the leader has an up-to-date log. Our recently crashed node has no logs at this point so it can't ensure leader safety. Likewise the other nodes would need to learn that our recently crashed node now has no logs and should not be counted towards a majority. We could theoretically handle all of this but it adds a lot of complexity.

**Comment by CrowdHailer** [comment]
>  If a node crashes there's no way for the rest of the nodes to know that its now lost all of its data and the other nodes will assume that it has all of its data still.

So if a node dies because the data centre falls into a volcano the rest of the network will assume the data is still durable? that seams a strange to me

**Comment by NeilMenne** [comment]
> If a node crashes there's no way for the rest of the nodes to know that its now lost all of its data and the other nodes will assume that it has all of its data still.

That's not technically true. Non-leaders will have no way of knowing because they don't communicate with each other about such things, but the next time the leader sends the `AppendEntries` RPC to the recently deceased, it will fail. The leader will then work its way backwards (in this case to zero) before attempting to send this node any log entries. This will create _a lot_ of unnecessary network traffic just because you're keeping things out of durable storage. Also, this makes the whole cluster's availability more precarious. Lose another node while you're getting caught up and you are moving ever closer to sacrificing availability unnecessarily as the leader can't consider a command committed until its been accepted by a majority of nodes.

> So if a node dies because the data centre falls into a volcano the rest of the network will assume the data is still durable? that seams a strange to me

The real problem with in memory backends is if the node has a hiccup in _any_ other part of the application such that the whole application goes down, it has to go through the same ordeal as if it had fallen into the aforementioned volcano.

**Comment by CrowdHailer** [comment]
> The real problem with in memory backends is if the node has a hiccup in any other part of the application such that the whole application goes down,

Ok thanks. In a system where I use supervision trees to separate the chance of one crash affecting other parts of the application this seams on alright. risk particularly as a recovery mode exists. even it expensive

**Comment by keathley** [comment]
> So if a node dies because the data centre falls into a volcano the rest of the network will assume the data is still durable? that seams a strange to me

My point here is that raft assumes that data is durable as a default. You're changing the semantics of the algorithm. But more importantly if one of the nodes crashes the other nodes won't know *immediately* that its crashed. They'll have to wait until they start trying to exchange rpcs, at which point the node that crashed would need to inform the other nodes that its no longer a voting member and should not be counted in elections, etc.

**Comment by keathley** [comment]
If you're still curious about the issues here I'd suggest reading sections 5.2 and 5.4 of the paper which deal with leader election safety. Specifically I would look at the description of the Leader Completeness Property. If you have other questions feel free to ask them.
